platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3.9-jdk-8
inputs:
  - name: repo
  - name: repo-ci
run:
  path: bash
  args:
  - -c
  - |
    repo-ci/tasks/deploy-s2-maven.sh repo
